### ISSUE TITLE
Exception retrieving machine info: 'data'

### ISSUE THREAD

**Issue by mitchej** [rccoleman/lamarzocco#25]
Am getting an error when attempting to use the LM integration. issue has started recently (perhaps after an update of Home Assistant to 9.5?)

`Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/lmdirect/connection.py", line 160, in _connect
    self._machine_info = await self.retrieve_machine_info(
  File "/usr/local/lib/python3.9/site-packages/lmdirect/connection.py", line 111, in retrieve_machine_info
    fleet = cust_info.json()["data"]["fleet"][0]
KeyError: 'data'`

Any ideas on what might be causing this?

**Comment by rccoleman** [comment]
Dup of https://github.com/rccoleman/lamarzocco/issues/23.
