### ISSUE TITLE
Linea Micra serial number error

### ISSUE THREAD

**Issue by ebfio** [rccoleman/lamarzocco#34]
Hi there! Thanks for all the work, this integration is amazing.

But I'm having an issue with my brand new Linea Micra (my Linea Mini works perfectly):

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/discovery_flow.py", line 71, in _async_start
    await gather_with_concurrency(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 199, in gather_with_concurrency
    return await gather(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 197, in sem_task
    return await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 225, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/lamarzocco/config_flow.py", line 111, in async_step_zeroconf
    serial_number: str = raw["serial_number"].decode("utf-8")
KeyError: 'serial_number' 
```

Let me know if I can share more information to help with this. Thank you!

**Comment by ebfio** [comment]
Closing this for now
